use etlclass;
select * from health_care_sql;

-- Retrieve the names of all patients in the database
select name from health_care_sql;

-- List the unique medical conditions present in the dataset
select count(distinct medical_condition) from health_care_sql;

-- Find the total number of doctors in the healthcare system
select count(distinct Doctor) from health_care_sql;

-- Retrieve the details of all female patient
select * from health_care_sql where gender = 'female';

-- what is the average age of patients in the database.
select avg(age) from health_care_sql;

--  Identify the patients who have more than one medical condition.
select name,count(Medical_Condition) from health_care_sql group by name having count(Medical_Condition)>1;

-- List the names of all doctors.
select Doctor from health_care_sql;

-- Identify the most common medical condition among patients.
select Medical_Condition,count(Name) from health_care_sql group by Medical_Condition order by count(name) desc limit 0,1;

-- Find the patients who are older than 60 years and have diabetes.
select name,age,Medical_condition from health_care_sql where age>60 and Medical_Condition='Diabetes';

-- Calculate the total revenue generated by the healthcare system.
select sum(billing_amount) from health_care_sql;

-- .Find the doctor with the oldest patient.
select doctor,name,age from health_care_sql order by age desc limit 5;

-- Calculate the average duration of medical visits.
select avg(duration) from health_care_sql;

-- Give the names of patients whose name starts with A
select name from health_care_sql where Name like 'A%';

-- How many male and female patients are there in dataset
select Gender,count(Gender) from health_care_sql group by Gender;

-- how many patients are normal.
select count(Test_results) from health_care_sql where test_results='normal';

-- .how many patients are abnormal or Inconclusive.
select count(Test_results) from health_care_sql where test_results='abnormal' or test_results='Inconclusive';

-- .how many patients of blood group AB+ are there of age above 52.
select name,blood_type,age from health_care_sql where age>52 and Blood_Type='AB+';

-- how many patients have paid the bill above 24890
select count(name) from health_care_sql where Billing_Amount>24890;

-- what are the names of patients having Asthma
select name,medical_condition from health_care_sql where Medical_Condition='Asthma';

-- how many patients have cancer
select count(name) from health_care_sql where Medical_Condition='cancer';

-- what are the names and blood groups of patients admitted to room no. 292.
select name,Blood_Type,Room_Number from health_care_sql where Room_Number = 292;

-- how many males have Arthritis
select count(name) from health_care_sql where Medical_Condition='arthritis' and Gender='male';

-- How many patients were admitted to Harris and Sons hospita
select count(distinct name) from health_care_sql where hospital='Harris and Sons';

-- what are the names of patients whose Insurance Provider are Cigna.
select name from health_care_sql where Insurance_Provider='Cigna';

-- Name the Medical Condition having patients whose ages is greater than average age
select Medical_Condition,avg(age) from health_care_sql group by Medical_Condition having avg(age)>52.1967;
select avg(age) from health_care_sql;
select medical_condition from health_care_sql;
